### ISSUE TITLE
bug: Hiding Short Components isn't working in v2.190.0 ReX Patches.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/ReX-patches#25]
### Type

Cosmetic

### Bug description

Hiding Like, Dislike, Share, Remix, Comments, etc cannot be hidden even after enabling hide options in setting.
YT version: 18.34.37 (recommended).
![Screenshot_2023-09-07-21-10-43-07_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/YT-Advanced/ReX-patches/assets/91815107/64f39d86-c806-4eb0-ac8c-477927f03000)
![Screenshot_2023-09-07-21-11-23-13](https://github.com/YT-Advanced/ReX-patches/assets/91815107/1c26f66e-1429-471d-82c6-428d18b6434a)

### Steps to reproduce

Just enable those hide options & play any short.

### Relevant log output

```shell
No logs.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Wojtaz0w** [comment]
I have exactly the same problem, i can only hide pivot button. Since yesterday. I heard it is a/b testing. Maybe of "live"  button in pause menu? Also im from Poland if thats important. 
![Screenshot_20230908-070238_YouTube.png](https://github.com/YT-Advanced/ReX-patches/assets/104674625/cf20befc-4081-42e8-ab26-a16a54da4ce1)
![Screenshot_20230908-070233_YouTube.png](https://github.com/YT-Advanced/ReX-patches/assets/104674625/98d87240-c916-4799-9188-da3be3428245)

**Comment by Aryan-Chauhan** [comment]
> I have exactly the same problem, i can only hide pivot button. Since yesterday. I heard it is a/b testing. Maybe of "live"  button in pause menu? Also im from Poland if thats important. 
> ![Screenshot_20230908-070238_YouTube.png](https://github.com/YT-Advanced/ReX-patches/assets/104674625/cf20befc-4081-42e8-ab26-a16a54da4ce1)
> ![Screenshot_20230908-070233_YouTube.png](https://github.com/YT-Advanced/ReX-patches/assets/104674625/98d87240-c916-4799-9188-da3be3428245)
> 
> 
> 
> 

I found a workaround.
Use YT version 18.33.40

**Comment by YT-Advanced** [comment]
Thanks for your report, I will check the problem and notify soon
